displayErrorDetails: true
addContentLengthHeader: false

# db settings
db:
    host: localhost
    port: 3306
    database: guestbook
    user: root
    password: root


# template rendering
renderer:
    template_path: %root_dir%/../templates/

# monolog
logger:
    name: slim-app
    path: %root_dir%/../logs/app.log
    level: debug